name: 'Snyk Get Projects'
description: 'Get All Snyk project'
inputs:
  api_token:
    description: 'Snyk API token'
    required: true
  project_id:
    description: "Snyk project id"
    required: true
    default: "-"
  org_id:
    description: "Snyk Organization ID"
    required: true
    default: "-"
runs:
  using: 'node16'
  main: 'index.js'